services:
  frontend:
    image: talhaejaz0/task-manager-frontend:latest
    container_name: task-frontend
    ports:
      - "3000:80"
    restart: always
    networks:
      - todo-network

  backend:
    image: talhaejaz0/task-manager-backend:latest
    container_name: task-backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: "mongodb+srv://hani:hani0817@cluster0.hhrwib9.mongodb.net/tasks-management?retryWrites=true&w=majority"
    restart: always
    networks:
      - todo-network

networks:
  todo-network: