name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

#  BUILD & PUSH IMAGES  #
      - name: Build images using docker-compose
        run: docker compose build --no-cache

      - name: Push images to Docker Hub
        run: docker compose push

      # ---------------- PREPARE SSH KEY ---------------- #
      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > my-ec2-key
          chmod 600 my-ec2-key

      # ---------------- DEPLOY TO EC2 ---------------- #
      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i my-ec2-key ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/project
            docker compose pull
            docker compose up -d
          EOF